import './globals.css'
import 'ui/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cn from 'classnames'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'bg-background text-text w-screen h-screen'
        )}>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
